spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:changelog/master.xml
    enabled: 'true'
    drop-first: 'false'
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/library
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.apache.kafka.common.serialization.LongSerializer

message:
  topic:
    name: free-book-info
  group-id: book-info

server:
  port: 8081
