version: "3.9"

services:
  postgres:
    container_name: "postgres"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - "library"

networks:
  library:
    driver: "bridge"
