spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  liquibase:
    change-log: classpath:changelog/master.xml
    enabled: 'true'
    drop-first: 'false'
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/library
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
app:
  security:
    secret-key: 472B4B6250655368566D597133743677397A244326452948404D635166546A57
    session-time: '120000000'

#hibernate:
#  dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: '8080'

